version: "3.8"

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: nextjs-web
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379

  worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile.worker
    container_name: worker
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379